Repository inspirezonetech/TeachMeCLikeIm5, pull requests merged in 2021-11, with the labels that each got.

#73 feat: passing-arguments C tutorial
  7-functions/passing-arguments.c
Labels: hacktoberfest-accepted, change required before merge!

#75 HeaderFiles C Tutorial
  10-preprocessors/headerfiles.c
Labels: hacktoberfest-accepted

#80 pointer arithmetic tutorial
  8-pointers/pointer-arithmetics.c
Labels: change required before merge!

#78 Ternary operator
  3-conditions/ternary-operator.c
Labels: hacktoberfest-accepted, change required before merge!
